# theme: jekyll-theme-minimal
title: lucasvieites' knowledge base
description: Here's where I keep my stuff so I don't need to remember it
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
